### ISSUE TITLE
Come up with a style class naming strategy for use in design sample styles - bcgov specific or not?

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/design-system#102]
Which is better: 

`.checkbox`

or 

`.bc-gov-checkbox` ?

Discuss.

**Comment by dlevineBC** [comment]
Having some kind of specific prefix like `bc` or `bc-gov` would be needed so our styles don't get overwritten. 

Do you know what best practices are? lower case us sentence case, underline vs dash?

**Comment by dlevineBC** [comment]
Been looking into BEM (block element modifier) naming convention: 

Block: `bc` or `bcgov` (I think I prefer bcgov)
Element: `btn`
Modifier: `secondary`

Australia uses the modifier with two dashes to distinguish between the modifier and a two worded element

`call-out--warning` vs `call-out-warning`

I prefer all lowercase with dashes instead of underlines

**Comment by dlevineBC** [comment]
@sheaphillips I moved this into in progress since I'm technically now working on it by doing some research. I'd like to come to some decision on this by end of sprint so we don't need to go back and fix things as we develop more components. What do you think about my comment above?

@orinevares what are your thoughts?

**Comment by orinevares** [comment]
I would agree that creating the most unique classes could be best so it does not interact with other common class names. I would say the two dashes for the modifier is unnecessary unless there is an actual technical reason behind this.

Therefore I would say that bcgov would be ideal so for secondary button 

'bcgov-btn-secondary'

**Comment by sheaphillips** [comment]
there's a longer discussion around why this shouldn't matter, but, if we do need a prefix, then developers would be most familiar lowercase chunks separated by dashes.

**Comment by dlevineBC** [comment]
DOD - update design system components to this class naming structure
