### ISSUE TITLE
Icon page - sizing and broken links

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#161]
## Which Component Has the Bug?
> Icons

## Describe the bug
> The icons are huge and some icon paths are broken

## Expected Behavior (if applicable)
Icons should be smaller sized, closer to 50px

**Comment by patricksimonian** [comment]
As per issue https://github.com/bcgov/devhub-app-web/issues/454. 

This was created by @matthewhall78 .
It looks like you guys have already created an issue for this. I'm not sure if this is still relevant but here is the original issue content below!
---
Broken Font Awesome icons

To Reproduce
Steps to reproduce the behavior:

Go to https://developer.gov.bc.ca/Design-System/Icons
icons are not displaying
Expected behavior
icons are showing

Solution
Font awesome has built a shim so you can fix them while you give yourself time to upgrade to v5 of font awesome. https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4
```html
<head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/v4-shims.css">
</head>
<body>
  <!-- "close" is an alias to "times", V5 is <i class="fa fa-times"></i> -->
  <i class="fa fa-close"></i>

  <!-- Renamed to "image", V5 is <i class="fa fa-image"></i> -->
  <i class="fa fa-picture"></i>

  <!-- Needs the "fab" prefix, V5 <i class="fab fa-twitter"></i> -->
  <i class="fa fa-twitter"></i>

  <!-- "far" prefix, lose the "-o", V5 <i class="far fa-circle"></i> -->
  <i class="fa fa-circle-o"></i>
</body>  
```

**Comment by dlevineBC** [comment]
@orinevares If there isn't a simple fix to get these sized properly (which I'm not sure how to do in the Markdown file), please remove the table of icons until we can put together a solution that works. I don't want this page to continue showing broken links and giant images

**Comment by matthewhall78** [comment]
I took a look at this earlier today.  The icons will dynamically size based on the table space you provide it. The problem seems to be that you have used <table><tr><td> tags instead of the bootstrap table col classes. if you restrict the icon column to 2 or 3 out of 12 then the sizing should be kept under control.

**Comment by patricksimonian** [comment]
the tables are generated from a markdown file so it gets difficult to control via bootstrap styles. One thing i'd suggest is perhaps using smaller png files. If you take a look at the png files you are sourcing they are HUGE! great for resolution, but i doubt icons would ever need to be that big. Perhaps restricting them to be no wider than 40 px while stile maintaining their aspect ratio?

**Comment by patricksimonian** [comment]
Also as an aside, we are exploring a framework called Docz for the design system https://www.docz.site/

It allows to embed react components into markdown which will make a lot of this much easier to deal with :)
