### ISSUE TITLE
Use of rem instead of px in CSS.

### ISSUE THREAD

**Issue by ShawnTurple** [bcgov/design-system#220]
## Which Component Has the Bug?
> Button, but all other components will be effected.

## Describe the bug
When defining the following, rem should be considered instead of px;

- letter-spacing
- font-size
- padding
- margin
- etc..

## Other Information
The main body font size should be in px.
If a body font size was 18px then a padding for a button might be padding: 0.75rem 1.5rem;

## Resources
https://medium.com/code-better/css-units-for-font-size-px-em-rem-79f7e592bb97
https://www.w3schools.com/bootstrap4/bootstrap_typography.asp

**Comment by orinevares** [comment]
Hi Shawn,

Thank you for your contribution! 

We have decided to hold off on this change for now since currently the design system code is not working as a "system." By system we mean that the code would operate as something similar to a bootstrap framework and users can just load it through packages or cdns. Therefore, if people are to copy and paste the code as it is now, it could reference a base font size that is not the same as what the design system recommends, and skew the button design. Once we create a code system that actually works together we will update the spacing from px to rems.
