### ISSUE TITLE
Design System v1: Inconsistent link colors on DevHub

### ISSUE THREAD

**Issue by desagner2** [bcgov/design-system#281]
> path: (do not delete) https://github.com/bcgov/design-system/blob/master/components/about/about.md
 > (do not delete) devhub page: undefined

## Devhub Content Issue

Your hyperlinks (design systems) are all inconsistent. Some are bright blue, some are dark blue, some have the underlines and some not. Please review this documentation. Thanks! :)

**Comment by ty2k** [comment]
Hey @desagner2, thanks for filing this issue.

The [Links page of the design system on DevHub](https://developer.gov.bc.ca/Design-System/Links) is confusing because DevHub (the site hosting the design system content) does not actually implement the guidance in the design system 100%. For best results, follow the [CSS code sample on that page](https://developer.gov.bc.ca/Design-System/Links#css) as opposed to the look and feel of DevHub.

Please note that we have a new major version of the design system in the works, and we have the first new piece of content for this system launched here: [Figma community file for B.C. Design Tokens](https://www.figma.com/community/file/1326994583954765832)

The suggested link color in the new system is the same as the previous system: `#1a5a96`

**Comment by desagner2** [comment]
This is very helpful! Thanks so much =)))

**Comment by ty2k** [comment]
Sounds great! I'll close this issue now, but feel free to reach out in another issue or by email (DesignSystem@gov.bc.ca) if we can assist further.
