### ISSUE TITLE
Cross-publish package and release notes to GitHub

### ISSUE THREAD

**Issue by mkernohanbc** [bcgov/design-system#333]
Given we know that [@bcgov/design-system](https://github.com/bcgov/design-system) is the most visible surface we have for the DS, I'd like us to explore how we can boost visibility and discoverability of releases and changelogs on the front page of the repo using GitHub's 'Releases' and 'Packages' features:

![Image](https://github.com/bcgov/design-system/assets/135075821/7726ab42-2889-41d7-8157-a5ea397fe305)

It appears that GitHub [supports cross-publishing packages from npm to GitHub packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry), with a couple of changes to `package.json`?

It would also be good if we could explore how we can sync changelogs/release notes to GitHub Releases. We don't currently have changelogs available on npm, so we should have a conversation about where the source of truth for this should be.

I don't think this is blocking to 3.0.0 release, but if we have bandwidth to investigate and discuss before release, it seems like a good bit of housekeeping to do sooner rather than later.

**Comment by mkernohanbc** [comment]
Based on this morning's conversation, putting this into deep freeze for the time being. We'll stick to package-level changelog.md files for now, and can potentially revisit in a better-resourced future.

**Comment by ty2k** [comment]
I've added tags with `git tag` and Releases using GitHub's UI so that our existing npm versions show up in the releases section of the repo homepage:

<img width="342" alt="Releases section of bcgov/design-system repo" src="https://github.com/bcgov/design-system/assets/25143706/2f266f43-87db-44e7-be02-ea79cb740827">

Each release has its associated changelog details included, with a link to the package on npm:

<img width="1840" alt="Release details screen" src="https://github.com/bcgov/design-system/assets/25143706/359a91f9-6979-4483-a2e3-56cc9842a970">

For now, this process is completely manual. When we `npm publish` a new version of one of the packages, we will need to `git tag` using the equivalent commit, push that tag to the repo with `git push --tags`, and then use GitHub's UI to add a new Release. As our process matures, we can look at automating more of this in the future.

We're still not doing anything with GitHub's Packages feature, which duplicates npm's package repository function.
