### ISSUE TITLE
Beta Status for Applications

### ISSUE THREAD

**Issue by dlevineBC** [bcgov/design-system#78]
## What
Label that shows the application is in a "Beta" phase

## Why
Many applications being built are using agile developed and are released to the public but aren't "finished". 
There is a need to indicate that an application is in a Beta state so that users understand it isn't fully done.

## Anything else
Must be persistent on all page views, so probably should be put in the header

**Comment by dlevineBC** [comment]
The UK gov calls this a "Phase banner"

> Phase banner
> Use the phase banner component to show users your service is still being worked on.

<img width="545" alt="uk" src="https://user-images.githubusercontent.com/29607430/51570654-70333100-1e54-11e9-868a-a5bacf62a0df.png">

**Comment by dlevineBC** [comment]
The Cannabis licensing application currently has a "beta" sticker 

<img width="687" alt="beta-cannabis" src="https://user-images.githubusercontent.com/29607430/51570704-a2449300-1e54-11e9-9845-862567ff3ed9.png">

The outlined badge risks looking like a "ghost button"

**Comment by dlevineBC** [comment]
The new OrgBookBC list service indicates that the beta is a "public beta". We don't have the concept of a private beta at this time, I don't think this specificity is required.

<img width="481" alt="public-beta" src="https://user-images.githubusercontent.com/29607430/51570789-e6379800-1e54-11e9-8ba0-d74c6a4a5d45.png">

**Comment by dlevineBC** [comment]
The Australis design system is currently in Beta. They use a much more rounded pill style. Looks less like a button

<img width="377" alt="australia" src="https://user-images.githubusercontent.com/29607430/51570867-23038f00-1e55-11e9-90b0-f2dff9a49b3d.png">

**Comment by dlevineBC** [comment]
There are three different ways to format the text. Sentencecase; Uppercase; Lowercase; 

- Beta

- BETA

- beta

**Comment by dlevineBC** [comment]
This is an Alpha badge - same concept but different "phase". I think this looks too much like a button 

<img width="284" alt="alpha" src="https://user-images.githubusercontent.com/29607430/51624733-53e4d200-1ef0-11e9-8c1a-4d1326ffce57.png">

**Comment by mark-walle** [comment]
I prefer the notion of a "[Phase Banner](https://design-system.service.gov.uk/components/phase-banner/)" component described by the Gov.uk design system.

The CMS.gov design system the phrase "[Badge](https://design.cms.gov/components/badge/)" to denote the same idea as Phase Banner.

<img width="476" alt="CMS gov Badges" src="https://user-images.githubusercontent.com/3486204/56060783-acbc4d80-5d1c-11e9-989d-3ae876e1e6a3.png">

Either Phase or Badge seems like it gains some more reusability as a component. A product team might like to use the phase/badge to tag the environment to which a system is deployed.

For example, most lab teams working on OpenShift deploy their systems into Dev, Test, QA, and Prod environments. This is typically indicated in the URLs as: `projectname.environment.pathfinder.gov.bc.ca`, until they reach Production where the '`prod` environoment subdomain indicator is dropped, like: `projectname.gov.bc.ca`. Having a _badge_ to indicate to a QA user that they are presently in the QA deployment of the system is more helpful than that user having to examine the URL in order to orient themselves.

If going with the reusable component _phase_ or _badge_, it will need appropriate guidances to ensure they get reused appropriately. One particular guidance might be something like "use a yellow Badge to indicate a product that is in Beta".

Phases/badges could then be sub-typed to further denote particular use-cases: in the previous example I used "yellow" for the Beta Status badge, but that could just as easily be the "warning" badge (the term used at https://design.cms.gov/components/badge/)

**Comment by mark-walle** [comment]
The [DevHub](https://developer.gov.bc.ca/) banner itself currently has the Beta Status component indicated. Since there are multiple product teams working on different products (termed "collections" on that page) which all share the DevHub banner, can the Beta Status indicator only be removed once all those product teams deem that appropriate?

Using the Phases or Badge indicators more like what's defined in my previous comment, you can tag products that fall under a collective banner as Beta or not. As in (and I apologize for this very rough rendering):

<img width="429" alt="Badge beta" src="https://user-images.githubusercontent.com/3486204/56063781-1b050e00-5d25-11e9-982f-b6bf33df2790.png">

This way, DevHub can be out of Beta, while the Design system is still in beta.

**Comment by dlevineBC** [comment]
Thanks for the comments @mark-walle 
One thing we need to better explore around the beta badge is the ability to provide information on what it means to users and a way to provide feedback, which I think is why the UK phase banner is more successful than what we have now and will impact the future design.

Because the beta status is a unique pattern (a component applied to a specific use case), I wouldn't want to immediately combine that pattern with a badge component as being the same thing.

I'm going to put in a new component in the backlog for Badges, but for the time being the badge won't be lumped together with the beta status. As we do more research into beta status the design of the badge could end up supporting the beta pattern.
